ALTER TABLE jobs ADD COLUMN IF NOT EXISTS trust_score FLOAT DEFAULT 0.0;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS is_spam BOOLEAN DEFAULT FALSE;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS spam_reason TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS company_tier INTEGER DEFAULT 3;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS is_faang BOOLEAN DEFAULT FALSE;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS is_internship BOOLEAN DEFAULT FALSE;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS is_hybrid BOOLEAN DEFAULT FALSE;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS work_mode TEXT;
ALTER TABLE jobs ADD COLUMN IF NOT EXISTS is_student_eligible BOOLEAN DEFAULT FALSE;
